// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt_Sii_WK.Entities;

namespace Projekt_Sii_WK.Migrations
{
    [DbContext(typeof(SerwisDbContext))]
    partial class SerwisDbContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Projekt_Sii_WK.Entities.Klient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numer_tel")
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    b.Property<int>("PojazdId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("Projekt_Sii_WK.Entities.Pojazd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Marka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rejestracja")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id");

                    b.ToTable("Pojazdy");
                });

            modelBuilder.Entity("Projekt_Sii_WK.Entities.Serwis_samoch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Garaz")
                        .HasColumnType("int");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<int>("PojazdId")
                        .HasColumnType("int");

                    b.Property<string>("Pracownik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rodzaj_wady")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlientId")
                        .IsUnique();

                    b.HasIndex("PojazdId")
                        .IsUnique();

                    b.ToTable("Serwis");
                });

            modelBuilder.Entity("Projekt_Sii_WK.Entities.Serwis_samoch", b =>
                {
                    b.HasOne("Projekt_Sii_WK.Entities.Klient", "Klient")
                        .WithOne("Serwis_samoch")
                        .HasForeignKey("Projekt_Sii_WK.Entities.Serwis_samoch", "KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt_Sii_WK.Entities.Pojazd", "Pojazd")
                        .WithOne("Serwis_samoch")
                        .HasForeignKey("Projekt_Sii_WK.Entities.Serwis_samoch", "PojazdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");

                    b.Navigation("Pojazd");
                });

            modelBuilder.Entity("Projekt_Sii_WK.Entities.Klient", b =>
                {
                    b.Navigation("Serwis_samoch");
                });

            modelBuilder.Entity("Projekt_Sii_WK.Entities.Pojazd", b =>
                {
                    b.Navigation("Serwis_samoch");
                });
#pragma warning restore 612, 618
        }
    }
}
